name: payable_ipg
description: PAYable IPG
version: 0.0.1
repository: https://github.com/flutter/packages/tree/main/packages/adaptive_scaffold

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0