name: payable_ipg_flutter
description: PAYable IPG SDK for Flutter
version: 2.1.0
repository: https://github.com/payable/flutter-ipg
homepage: https://flutter-ipg.payable.lk

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  http: ^1.2.1
  package_info_plus: ^8.0.0
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0